### ISSUE TITLE
QGIS3 port?

### ISSUE THREAD

**Issue by rduivenvoorde** [Lytrix/pdokbaggeocoder#10]
Hi Eelke,
Any plans for QGIS3?
Or should I just try :-)
Richard

**Comment by maas2** [comment]
Would be great to see it in QGIS3!!

Op ma 3 jun. 2019 20:20 schreef Richard Duivenvoorde <
notifications@github.com>:

**Comment by maas2** [comment]
Hi, are there plans for implementation in QGGIS 3? I am going back to 2.18
sometimes, just to geocode....

Op ma 3 jun. 2019 21:21 schreef Maas Kanaal <noorlandt.maas@gmail.com>:

**Comment by Bastiaandupon** [comment]
Hi Eelke,

A lot of our 'colleages' would love to see this in Qgis3, now it is patched in the Amsterdam Digital Workspace (ADW). Questions are rising now.
Need of any help??
Bastiaan

**Comment by maas2** [comment]
Hi,

I for one would really love to see it in GGIS3!

Op ma 28 okt. 2019 10:41 schreef Bastiaandupon <notifications@github.com>:
