### ISSUE TITLE
Error Baggeocoder 

### ISSUE THREAD

**Issue by Bergstra** [Lytrix/pdokbaggeocoder#7]
Hallo,
Ik krijg de volgende foutmelding: 
![image](https://user-images.githubusercontent.com/38730989/39258462-49e5f99a-48b4-11e8-9d43-435a3cd6694d.png)
Is dit een bug? Elke keer nadat een paar adressen zijn gegeocodeerd krijg ik deze foutmeldingen en moet ik op OK klikken om door te gaan. Ongeveer de helft van de adressen wordt gegeocodeerd.  
MMQGIS werkt wel goed, geen foutmeldingen.

Alvast bedankt voor het beantwoorden van mijn vraag.

Groeten 

Arnold

**Comment by rduivenvoorde** [comment]
Hoi Arnold,

zie #8 je moet even de print statements in pdokbaggeocoder_library.py in commentaar zetten, die geven de foutmelding (hoewel het geocodere wel goed gaat)

**Comment by Bergstra** [comment]
Hoi Richard, 
Bedankt voor het advies. Het aanpassen is gelukt en het geocoderen doet het nu zonder foutmeldingen. 

Groeten 
Arnold
