### ISSUE TITLE
Housenumbers under 100 are not geocoded

### ISSUE THREAD

**Issue by maas2** [Lytrix/pdokbaggeocoder#9]
Geocoding is up and running, thanks!
However, housenumbers under 100 are not geocoded. 
Those numers are combined to one point.

**Comment by Lytrix** [comment]
@maas2 Thanks for catching that bug. It was caused by a default higher score of the type:weg in the api. I changed the api query to give the type:adres a higher score, so it now works as excepted again. The new version should be available tomorrow.

**Comment by maas2** [comment]
Dank je wel! Ik gebruik de plugin veelvuldig....

Op wo 23 mei 2018 23:49 schreef Eelke Jager <notifications@github.com>:
